import { Continent, GeoType } from "./types";

export const geoList: GeoType[] = [
  {
    nameEng: "Afghanistan",
    nameUkr: "Афганістан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Albania",
    nameUkr: "Албанія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Algeria",
    nameUkr: "Алжир",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "American Samoa",
    nameUkr: "Американське Самоа",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Andorra",
    nameUkr: "Андорра",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Angola",
    nameUkr: "Ангола",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Anguilla",
    nameUkr: "Ангілья",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },

  {
    nameEng: "Antarctica",
    nameUkr: "Антарктида",
    continentEng: "Antarctica",
    continentUkr: "Антарктида",
  },
  {
    nameEng: "Antigua and Barbuda",
    nameUkr: "Антигуа і Барбуда",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Argentina",
    nameUkr: "Аргентина",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Armenia",
    nameUkr: "Вірменія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Aruba",
    nameUkr: "Аруба",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Australia",
    nameUkr: "Австралія",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Austria",
    nameUkr: "Австрія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Azerbaijan",
    nameUkr: "Азербайджан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Bahamas",
    nameUkr: "Багами",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Bahrain",
    nameUkr: "Бахрейн",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Bangladesh",
    nameUkr: "Бангладеш",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Barbados",
    nameUkr: "Барбадос",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Belarus",
    nameUkr: "Білорусь",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Belgium",
    nameUkr: "Бельгія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Belize",
    nameUkr: "Беліз",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Benin",
    nameUkr: "Бенін",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Bermuda",
    nameUkr: "Бермуди",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Bhutan",
    nameUkr: "Бутан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Bolivia (Plurinational State of)",
    nameUkr: "Болівія",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Bonaire, Sint Eustatius and Saba",
    nameUkr: "Бонайре, Сінт-Естатіус і Саба",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Bosnia and Herzegovina",
    nameUkr: "Боснія і Герцеговина",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Botswana",
    nameUkr: "Ботсвана",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Bouvet Island",
    nameUkr: "Острів Буве",
    continentEng: "Antarctica",
    continentUkr: "Антарктида",
  },
  {
    nameEng: "Brazil",
    nameUkr: "Бразилія",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "British Indian Ocean Territory",
    nameUkr: "Британська територія в Індійському океані",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Brunei Darussalam",
    nameUkr: "Бруней",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Bulgaria",
    nameUkr: "Болгарія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Burkina Faso",
    nameUkr: "Буркіна-Фасо",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Burundi",
    nameUkr: "Бурунді",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Cabo Verde",
    nameUkr: "Кабо-Верде",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Cambodia",
    nameUkr: "Камбоджа",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Cameroon",
    nameUkr: "Камерун",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Canada",
    nameUkr: "Канада",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Cayman Islands",
    nameUkr: "Кайманові Острови",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Central African Republic",
    nameUkr: "Центральноафриканська Республіка",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Chad",
    nameUkr: "Чад",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Chile",
    nameUkr: "Чілі",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "China",
    nameUkr: "Китай",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Christmas Island",
    nameUkr: "Острів Різдва",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Cocos (Keeling) Islands",
    nameUkr: "Кокосові (Кілінг) Острови",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Colombia",
    nameUkr: "Колумбія",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Comoros",
    nameUkr: "Коморські Острови",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Congo (the Democratic Republic of the)",
    nameUkr: "Конго (Демократична Республіка)",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Congo",
    nameUkr: "Конго",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Cook Islands",
    nameUkr: "Острови Кука",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Costa Rica",
    nameUkr: "Коста-Ріка",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Croatia",
    nameUkr: "Хорватія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Cuba",
    nameUkr: "Куба",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Curaçao",
    nameUkr: "Кюрасао",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Cyprus",
    nameUkr: "Кіпр",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Czechia",
    nameUkr: "Чехія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Côte d'Ivoire",
    nameUkr: "Кот-д'Івуар",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Denmark",
    nameUkr: "Данія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Djibouti",
    nameUkr: "Джибуті",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Dominica",
    nameUkr: "Домініка",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Dominican Republic",
    nameUkr: "Домініканська Республіка",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Ecuador",
    nameUkr: "Еквадор",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Egypt",
    nameUkr: "Єгипет",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "El Salvador",
    nameUkr: "Сальвадор",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Equatorial Guinea",
    nameUkr: "Екваторіальна Гвінея",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Eritrea",
    nameUkr: "Еритрея",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Estonia",
    nameUkr: "Естонія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Eswatini",
    nameUkr: "Есватіні",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Ethiopia",
    nameUkr: "Ефіопія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Falkland Islands [Malvinas]",
    nameUkr: "Фолклендські (Мальвінські) Острови",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Faroe Islands",
    nameUkr: "Фарерські Острови",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Fiji",
    nameUkr: "Фіджі",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Finland",
    nameUkr: "Фінляндія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "France",
    nameUkr: "Франція",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "French Guiana",
    nameUkr: "Французька Гвіана",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "French Polynesia",
    nameUkr: "Французька Полінезія",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "French Southern Territories",
    nameUkr: "Французькі Південні Території",
    continentEng: "Antarctica",
    continentUkr: "Антарктида",
  },
  {
    nameEng: "Gabon",
    nameUkr: "Габон",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Gambia",
    nameUkr: "Гамбія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Georgia",
    nameUkr: "Грузія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Germany",
    nameUkr: "Німеччина",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Ghana",
    nameUkr: "Гана",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Gibraltar",
    nameUkr: "Гібралтар",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Greece",
    nameUkr: "Греція",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Greenland",
    nameUkr: "Гренландія",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Grenada",
    nameUkr: "Гренада",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Guadeloupe",
    nameUkr: "Гваделупа",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Guam",
    nameUkr: "Гуам",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Guatemala",
    nameUkr: "Гватемала",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Guernsey",
    nameUkr: "Гернсі",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Guinea",
    nameUkr: "Гвінея",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Guinea-Bissau",
    nameUkr: "Гвінея-Бісау",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Guyana",
    nameUkr: "Гаяна",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Haiti",
    nameUkr: "Гаїті",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Heard Island and McDonald Islands",
    nameUkr: "Острови Херд і Макдональд",
    continentEng: "Antarctica",
    continentUkr: "Антарктида",
  },
  {
    nameEng: "Holy See",
    nameUkr: "Святий Престол (Ватикан)",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Honduras",
    nameUkr: "Гондурас",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Hong Kong",
    nameUkr: "Гонконг",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Hungary",
    nameUkr: "Угорщина",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Iceland",
    nameUkr: "Ісландія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "India",
    nameUkr: "Індія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Indonesia",
    nameUkr: "Індонезія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Iran (Islamic Republic of)",
    nameUkr: "Іран",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Iraq",
    nameUkr: "Ірак",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Ireland",
    nameUkr: "Ірландія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Isle of Man",
    nameUkr: "Острів Мен",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Israel",
    nameUkr: "Ізраїль",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Italy",
    nameUkr: "Італія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Jamaica",
    nameUkr: "Ямайка",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Japan",
    nameUkr: "Японія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Jersey",
    nameUkr: "Джерсі",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Jordan",
    nameUkr: "Йорданія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Kazakhstan",
    nameUkr: "Казахстан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Kenya",
    nameUkr: "Кенія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Kiribati",
    nameUkr: "Кірібаті",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Korea (the Democratic People's Republic of)",
    nameUkr: "Корея (КНДР)",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Korea (the Republic of)",
    nameUkr: "Корея (Республіка Корея)",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Kuwait",
    nameUkr: "Кувейт",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Kyrgyzstan",
    nameUkr: "Киргизстан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Lao People's Democratic Republic",
    nameUkr: "Лаос",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Latvia",
    nameUkr: "Латвія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Lebanon",
    nameUkr: "Ліван",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Lesotho",
    nameUkr: "Лесото",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Liberia",
    nameUkr: "Ліберія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Libya",
    nameUkr: "Лівія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Liechtenstein",
    nameUkr: "Ліхтенштейн",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Lithuania",
    nameUkr: "Литва",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Luxembourg",
    nameUkr: "Люксембург",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Macao",
    nameUkr: "Макао",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Madagascar",
    nameUkr: "Мадагаскар",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Malawi",
    nameUkr: "Малаві",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Malaysia",
    nameUkr: "Малайзія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Maldives",
    nameUkr: "Мальдіви",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Mali",
    nameUkr: "Малі",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Malta",
    nameUkr: "Мальта",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Marshall Islands",
    nameUkr: "Маршаллові Острови",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Martinique",
    nameUkr: "Мартиніка",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Mauritania",
    nameUkr: "Мавританія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Mauritius",
    nameUkr: "Маврикій",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Mayotte",
    nameUkr: "Майотта",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Mexico",
    nameUkr: "Мексика",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Micronesia (Federated States of)",
    nameUkr: "Мікронезія",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Moldova (the Republic of)",
    nameUkr: "Молдова",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Monaco",
    nameUkr: "Монако",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Mongolia",
    nameUkr: "Монголія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Montenegro",
    nameUkr: "Чорногорія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Montserrat",
    nameUkr: "Монтсеррат",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Morocco",
    nameUkr: "Марокко",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Mozambique",
    nameUkr: "Мозамбік",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Myanmar",
    nameUkr: "М'янма",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Namibia",
    nameUkr: "Намібія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Nauru",
    nameUkr: "Науру",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Nepal",
    nameUkr: "Непал",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Netherlands",
    nameUkr: "Нідерланди",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "New Caledonia",
    nameUkr: "Нова Каледонія",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "New Zealand",
    nameUkr: "Нова Зеландія",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Nicaragua",
    nameUkr: "Нікарагуа",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Niger",
    nameUkr: "Нігер",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Nigeria",
    nameUkr: "Нігерія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Niue",
    nameUkr: "Ніуе",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Norfolk Island",
    nameUkr: "Острів Норфолк",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "North Macedonia",
    nameUkr: "Північна Македонія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Northern Mariana Islands",
    nameUkr: "Північні Маріанські Острови",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Norway",
    nameUkr: "Норвегія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Oman",
    nameUkr: "Оман",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Pakistan",
    nameUkr: "Пакистан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Palau",
    nameUkr: "Палау",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Palestine, State of",
    nameUkr: "Палестина",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Panama",
    nameUkr: "Панама",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Papua New Guinea",
    nameUkr: "Папуа Нова Гвінея",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Paraguay",
    nameUkr: "Парагвай",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Peru",
    nameUkr: "Перу",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Philippines",
    nameUkr: "Філіппіни",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Pitcairn",
    nameUkr: "Піткерн",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Poland",
    nameUkr: "Польща",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Portugal",
    nameUkr: "Португалія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Puerto Rico",
    nameUkr: "Пуерто-Рико",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Qatar",
    nameUkr: "Катар",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Romania",
    nameUkr: "Румунія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Russian Federation",
    nameUkr: "Росія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Rwanda",
    nameUkr: "Руанда",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Réunion",
    nameUkr: "Реюньйон",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Saint Barthélemy",
    nameUkr: "Сен-Бартельмі",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Saint Helena, Ascension and Tristan da Cunha",
    nameUkr: "Острів Святої Єлени, Вознесіння і Тристан-да-Кунья",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Saint Kitts and Nevis",
    nameUkr: "Сент-Кіттс і Невіс",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Saint Lucia",
    nameUkr: "Сент-Люсія",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Saint Martin (French part)",
    nameUkr: "Сен-Мартен",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Saint Pierre and Miquelon",
    nameUkr: "Сен-П'єр і Мікелон",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Saint Vincent and the Grenadines",
    nameUkr: "Сент-Вінсент і Гренадіни",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Samoa",
    nameUkr: "Самоа",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },

  {
    nameEng: "San Marino",
    nameUkr: "Сан-Марино",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Sao Tome and Principe",
    nameUkr: "Сан-Томе і Прінсіпі",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Saudi Arabia",
    nameUkr: "Саудівська Аравія",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Senegal",
    nameUkr: "Сенегал",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Serbia",
    nameUkr: "Сербія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Seychelles",
    nameUkr: "Сейшельські Острови",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Sierra Leone",
    nameUkr: "Сьєрра-Леоне",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Singapore",
    nameUkr: "Сінгапур",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Sint Maarten (Dutch part)",
    nameUkr: "Сінт-Маартен (голландська частина)",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Slovakia",
    nameUkr: "Словаччина",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Slovenia",
    nameUkr: "Словенія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Solomon Islands",
    nameUkr: "Соломонові Острови",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Somalia",
    nameUkr: "Сомалі",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "South Africa",
    nameUkr: "Південна Африка",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "South Georgia and the South Sandwich Islands",
    nameUkr: "Південна Джорджія і Південні Сандвічеві острови",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "South Sudan",
    nameUkr: "Південний Судан",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Spain",
    nameUkr: "Іспанія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Sri Lanka",
    nameUkr: "Шрі-Ланка",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Sudan",
    nameUkr: "Судан",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Suriname",
    nameUkr: "Сурінам",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Svalbard and Jan Mayen",
    nameUkr: "Шпіцберген і Ян-Маєн",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Sweden",
    nameUkr: "Швеція",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Switzerland",
    nameUkr: "Швейцарія",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "Syrian Arab Republic",
    nameUkr: "Сирійська Арабська Республіка",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Taiwan",
    nameUkr: "Тайвань",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Tajikistan",
    nameUkr: "Таджикистан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Tanzania, United Republic of",
    nameUkr: "Танзанія, Об'єднана Республіка",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Thailand",
    nameUkr: "Таїланд",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Timor-Leste",
    nameUkr: "Тімор-Лешті",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Togo",
    nameUkr: "Того",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Tokelau",
    nameUkr: "Токелау",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Tonga",
    nameUkr: "Тонга",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Trinidad and Tobago",
    nameUkr: "Тринідад і Тобаго",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Tunisia",
    nameUkr: "Туніс",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Turkey",
    nameUkr: "Туреччина",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Turkmenistan",
    nameUkr: "Туркменістан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Turks and Caicos Islands",
    nameUkr: "Острови Теркс і Кайкос",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Tuvalu",
    nameUkr: "Тувалу",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Uganda",
    nameUkr: "Уганда",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Ukraine",
    nameUkr: "Україна",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "United Arab Emirates",
    nameUkr: "Об'єднані Арабські Емірати",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "United Kingdom of Great Britain and Northern Ireland",
    nameUkr: "Об'єднане Королівство Великої Британії та Північної Ірландії",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
  {
    nameEng: "United States Minor Outlying Islands",
    nameUkr: "Малі Віддалені Острови Сполучених Штатів",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "United States of America",
    nameUkr: "Сполучені Штати Америки",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Uruguay",
    nameUkr: "Уругвай",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Uzbekistan",
    nameUkr: "Узбекистан",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Vanuatu",
    nameUkr: "Вануату",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Venezuela (Bolivarian Republic of)",
    nameUkr: "Венесуела (Боліваріанська Республіка)",
    continentEng: "South America",
    continentUkr: "Південна Америка",
  },
  {
    nameEng: "Viet Nam",
    nameUkr: "В'єтнам",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Virgin Islands (British)",
    nameUkr: "Віргінські острови (Британські)",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Virgin Islands (U.S.)",
    nameUkr: "Віргінські острови (США)",
    continentEng: "North America",
    continentUkr: "Північна Америка",
  },
  {
    nameEng: "Wallis and Futuna",
    nameUkr: "Уолліс і Футуна",
    continentEng: "Oceania",
    continentUkr: "Океанія",
  },
  {
    nameEng: "Western Sahara",
    nameUkr: "Західна Сахара",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Yemen",
    nameUkr: "Ємен",
    continentEng: "Asia",
    continentUkr: "Азія",
  },
  {
    nameEng: "Zambia",
    nameUkr: "Замбія",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Zimbabwe",
    nameUkr: "Зімбабве",
    continentEng: "Africa",
    continentUkr: "Африка",
  },
  {
    nameEng: "Åland Islands",
    nameUkr: "Аландські острови",
    continentEng: "Europe",
    continentUkr: "Європа",
  },
];

export const continentsArr: Continent[] = geoList.reduce(
  (acc: Continent[], curr: GeoType) => {
    const exists = acc.some((item) => item.continentEng === curr.continentEng);
    if (!exists) {
      acc.push({
        continentEng: curr.continentEng,
        continentUkr: curr.continentUkr,
      });
    }

    return acc;
  },
  []
);
